# Instructions: https://kubernetes.io/docs/setup/independent/install-kubeadm/

- hosts: kube-nodes
  tasks:

  - name: install base packages to install kubernetes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https

  - name: install kubernetes repository key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: make sure kubernetes repository is added
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: install kubernetes packages # TODO maybe implement hold for the packages below
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - kubelet=1.13.3-00
      - kubeadm=1.13.3-00
      - kubectl=1.13.3-00

